services:
  tracker-redis:
    image: docker.io/library/redis:8.8@sha256:0a972391db0b24ec336e35d1bc98b237237e26f82bf5120cf2f6b1688d1df973
    restart: unless-stopped
    container_name: tracker-redis
    command: [ "redis-server", "--requirepass", "mbta"]
    ports:
      - "6379:6379"
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/passwd:/etc/mosquitto/password_file"
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
