services:
  tracker-redis:
    image: docker.io/library/redis:8.6@sha256:e628485c98f8cfe942d8b6f34d461dabf069884bf18932ccbdd9dd9af20b1acc
    restart: unless-stopped
    container_name: tracker-redis
    command: [ "redis-server", "--requirepass", "mbta"]
    ports:
      - "6379:6379"
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/passwd:/etc/mosquitto/password_file"
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
