services:
  tracker-redis:
    image: docker.io/library/redis:8.6@sha256:0c341492924cad6f5483f9133e43bd6c51ecdecbcadfac5b51657393b6a7936c
    restart: unless-stopped
    container_name: tracker-redis
    command: [ "redis-server", "--requirepass", "mbta"]
    ports:
      - "6379:6379"
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/passwd:/etc/mosquitto/password_file"
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
