{
 "title": "Inky MBTA Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Route",
    "query": {
     "query": "label_values(imt_schedule_events_created,route_id)"
    }
   },
   {
    "name": "Stop",
    "query": {
     "query": "label_values(imt_schedule_events_created,stop)"
    }
   },
   {
    "name": "Action",
    "query": {
     "query": "label_values(imt_schedule_events_created,action)"
    }
   },
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(mbta_api_requests,endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Schedule Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(action) (imt_schedule_events_total{action=~\"$Action\", route_id=~\"$Route\", stop=~\"$Stop\"})",
     "legendFormat": "action={{ action }}"
    }
   ]
  },
  {
   "title": "Schedule Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(action) (rate(imt_schedule_events_total{action=~\"$Action\", route_id=~\"$Route\", stop=~\"$Stop\"}[$__rate_interval]))",
     "legendFormat": "{{ action }} rate"
    }
   ]
  },
  {
   "title": "Total Schedule Events with Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by(route_id) (imt_schedule_events_total{route_id=~\"$Route\"})",
     "legendFormat": "route={{ route_id }}"
    }
   ]
  },
  {
   "title": "Most Events Per Stop",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(stop) (imt_schedule_events_total{action=~\"$Action\", route_id=~\"$Route\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "{syslog_id=\"inky-mbta-tracker\"} | logfmt --keep-empty | route_id =~ `$Route` | stop =~ `$Stop` | action =~ `$Action`"
    }
   ]
  },
  {
   "title": "inky-mbta-tracker & components CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{name=~\"inky-mbta-tracker|tracker-redis|mosquitto|home-assistant\"}[$__rate_interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "inky-mbta-tracker & components Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"inky-mbta-tracker|tracker-redis|mosquitto|home-assistant\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "executions" } },
   "targets": [
    {
     "expr": "imt_tracker_executions_total{stop=~\"$Stop\"}",
     "legendFormat": "{{ stop }}"
    }
   ]
  },
  {
   "title": "Errors, Removed, Restarts",
   "type": "logs",
   "gridPos": { "h": 16, "w": 17, "x": 7, "y": 29 },
   "targets": [
    {
     "expr": "{syslog_id=\"inky-mbta-tracker\"} | label_format level=detected_level | level = `error`"
    },
    {
     "expr": "{syslog_id=\"inky-mbta-tracker\"} |~ `existing|saved|Restarting|Dropping`"
    }
   ]
  },
  {
   "title": "MBTA API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "mbta_api_requests{endpoint=~\"$Endpoint\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{syslog_id=\"inky-mbta-tracker\"}"
    }
   ]
  }
 ]
}