version: '3'

dotenv: ['.env']

tasks:
  check:
    cmds:
      - uv run ruff check inky-mbta-tracker
      - uv run mypy
  fix:
    cmds:
      - uv run ruff check --fix inky-mbta-tracker
      - uv run ruff check --fix compute_class_hashes.py
  format:
    cmds:
      - uv run ruff format inky-mbta-tracker
      - uv run ruff format compute_class_hashes.py
  run:
    cmds:
      - uv run inky-mbta-tracker
  prediction-api:
    cmds:
      - uv run inky-mbta-tracker --api-server
  logs:
    cmds:
      - uvx tail -f imt.log
  profile:
    cmds:
      - uvx scalene inky-mbta-tracker/main.py
  compute-class-hashes:
    cmds:
      - uv run compute_class_hashes.py
      - uv run ruff format inky-mbta-tracker/shared_types/class_hashes.py
  test:
    cmds:
      - uv run pytest
