version: '3'

dotenv: ['.env']

tasks:
  pyright:
    cmds:
     - uv run pyright
  check:
    cmds:
      - uv run ruff check inky-mbta-tracker
      - task: basedpyright
  fix:
    cmds:
      - uv run ruff check --fix inky-mbta-tracker
      - uv run ruff check --fix compute_class_hashes.py
  format:
    cmds:
      - uv run ruff format inky-mbta-tracker
      - uv run ruff format compute_class_hashes.py
  run:
    cmds:
      - uv run inky-mbta-tracker
  api-server:
    cmds:
      - uv run inky-mbta-tracker --api-server
  logs:
    cmds:
      - uvx tail -f imt.log
  profile:
    cmds:
      - uvx scalene inky-mbta-tracker/main.py
  compute-class-hashes:
    cmds:
      - uv run compute_class_hashes.py
      - uv run ruff format inky-mbta-tracker/shared_types/class_hashes.py
  clear-logs:
    cmds:
      - rm *.log
  test:
    cmds:
      - uv run pytest
  check-all:
    cmds:
      - task: format
      - task: fix
      - task: check
      - task: test
