version: '3'

dotenv: ['.env']

tasks:
  check:
    cmds:
      - uv run ruff check inky-mbta-tracker
      - uv run mypy
  fix:
    cmds:
      - uv run ruff check --fix inky-mbta-tracker
  format:
    cmds:
      - uv run ruff format inky-mbta-tracker
  run:
    cmds:
      - uv run python3 inky-mbta-tracker/main.py
  logs:
    cmds:
      - uvx tail -f imt.log
  profile:
    cmds:
      - uvx scalene inky-mbta-tracker/main.py
