version: '3'

dotenv: ['.env']

tasks:
  check:
    cmds:
      - uvx ruff check inky-mbta-tracker
  fix:
    cmds:
      - uvx ruff check --fix inky-mbta-tracker
  format:
    cmds:
      - uvx ruff format inky-mbta-tracker
  run:
    cmds:
      - uvx python3 inky-mbta-tracker/main.py
  logs:
    cmds:
      - uvx tail -f imt.log
  profile:
    cmds:
      - uvx scalene inky-mbta-tracker/main.py