version: '3'

dotenv: ['.env']

tasks:
  check:
    cmds:
      - ruff check inky-mbta-tracker

  fix:
    cmds:
      - ruff check --fix inky-mbta-tracker
  format:
    cmds:
      - ruff format inky-mbta-tracker
  run:
    cmds:
      - python3 inky-mbta-tracker/main.py
  profile:
    env:
      PYTHONPERFSUPPORT: "1"
    cmds:
      - python3 inky-mbta-tracker/main.py --profile_s 30
  logs:
    cmds:
      - tail -f imt.log
