from prometheus_client import Counter, Gauge

schedule_events = Counter(
    "imt_schedule_events", "Processed Schedule Events", ["action", "route_id", "stop"]
)

vehicle_events = Counter(
    "imt_vehicle_events", "Any updates to vehicles", ["action", "route_id"]
)

vehicle_speeds = Gauge(
    "imt_vehicle_speeds", "Vehicle speeds", ["route_id", "vehicle_id"]
)

tracker_executions = Counter("imt_tracker_executions", "Tracker Executions", ["stop"])

mbta_api_requests = Gauge(
    "mbta_api_requests", "Requests we are making to the MBTA API", ["endpoint"]
)

running_threads = Gauge("imt_active_threads", "Active Threads")

redis_commands = Gauge("imt_redis_cmds", "Redis commands made", ["name"])

queue_size = Gauge("imt_queue_size", "Schedule/vehicle queue size")

queue_processed_item = Gauge(
    "imt_queue_processed_item", "Queue processed item", ["item_type"]
)

track_predictions_generated = Counter(
    "imt_track_predictions_generated",
    "Track predictions generated by the predictor",
    ["station_id", "route_id", "prediction_method"],
)

track_predictions_cached = Counter(
    "imt_track_predictions_cached",
    "Track predictions served from cache",
    ["station_id", "route_id"],
)

track_prediction_confidence = Gauge(
    "imt_track_prediction_confidence",
    "Confidence score of track predictions",
    ["station_id", "route_id", "track_number"],
)

track_historical_assignments_stored = Counter(
    "imt_track_historical_assignments_stored",
    "Historical track assignments stored",
    ["station_id", "route_id", "track_number"],
)

track_pattern_analysis_duration = Gauge(
    "imt_track_pattern_analysis_duration_seconds",
    "Time taken to analyze track patterns",
    ["station_id", "route_id"],
)

track_predictions_validated = Counter(
    "imt_track_predictions_validated",
    "Track predictions validated against actual assignments",
    ["station_id", "route_id", "result"],
)
