name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  cache_repo: ghcr.io/cubismod/inky-mbta-tracker:cache
  repo: ghcr.io/cubismod/inky-mbta-tracker

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:
  build-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          username: cubismod
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ var.repo }}:${{ github.sha }},latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ var.cache_repo }}
          cache-to: type=registry,ref=${{ var.cache_repo }},mode=max
      - name: copy image
        uses: coscene-io/skopeo-copy-action@a5fc4f79f7453c14fd572b68d0cb8467014e9b13 # v1.0.0
        with:
          src-image: ghcr.io/cubismod/inky-mbta-tracker/inky-mbta-tracker:${{ github.sha }}
          dst-image: ghcr.io/cubismod/inky-mbta-tracker/inky-mbta-tracker-dev:${{ github.sha }}
          src-creds: cubismod:${{ secrets.GITHUB_TOKEN }}
          dst-creds: cubismod:${{ secrets.GITHUB_TOKEN }}
      - name: tag latest image
        uses: coscene-io/skopeo-copy-action@a5fc4f79f7453c14fd572b68d0cb8467014e9b13 # v1.0.0
        with:
          src-image: ghcr.io/cubismod/inky-mbta-tracker/inky-mbta-tracker-dev:${{ github.sha }}
          dst-image: ghcr.io/cubismod/inky-mbta-tracker/inky-mbta-tracker-dev:latest
          src-creds: cubismod:${{ secrets.GITHUB_TOKEN }}
          dst-creds: cubismod:${{ secrets.GITHUB_TOKEN }}
  pr-check:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          username: cubismod
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ var.repo }}:dev-${{ github.sha }},dev-latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ var.cache_repo }}
          cache-to: type=registry,ref=${{ var.cache_repo }},mode=max