name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write



on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:



jobs:
  build-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build Dockerfile
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: inky-mbta-tracker
          cache: true
          build_file: Dockerfile
          cache_registry: cache
          tag: ${{ github.sha }}
          tag_with_latest: true
  pr-check:
    if: startsWith(github.ref, "refs/pull/")
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build Dockerfile
        uses: aevea/action-kaniko@master
        with:
          image: inky-mbta-tracker-dev
          cache: true
          cache_registry: cache
          build_file: Dockerfile
          tag: ${{ github.sha }}
